### ISSUE TITLE
Oscillation for ‎DR-HAF003S and ‎DR-HAF001S

### ISSUE THREAD

**Issue by brentmw** [zyonse/homebridge-dreo#16] opened 2023-08-19 00:41 UTC
Oscillation button(s) for DR-HAF003S and ‎DR-HAF001S. Power level seems to work great!

**Comment by zyonse** [comment] 2023-08-21 18:28
Can you post a screenshot of the in-app controls?

**Comment by brentmw** [comment] 2023-08-21 18:46
![IMG_1092](https://github.com/zyonse/homebridge-dreo/assets/3922294/643deb90-af90-49d0-877d-cc1f06ec10ea)
![IMG_1091](https://github.com/zyonse/homebridge-dreo/assets/3922294/325f1c3c-cb3a-4a35-a222-ee4d32937119)
“Big Air” is DR-HAF003S and “Air Circulator” is DR-HAF001S

**Comment by zyonse** [comment] 2023-08-24 15:17
Are you on iOS 17? When you tap the settings icon it should show an oscillation toggle.

**Comment by brentmw** [comment] 2023-09-01 00:06
> Are you on iOS 17? When you tap the settings icon it should show an oscillation toggle.

I have 1 device on iOS 17 and 3 others on 16. Neither of them have the oscillation option.

**Comment by zyonse** [comment] 2023-09-06 22:31
Can you enable debug mode for homebridge and post the console output here? Make sure you redact your username/password.

**Comment by zyonse** [comment] 2023-09-20 18:05
Can you click the settings icon next to the plugin in homebridge and install the beta version I just released? Let me know if that fixes it.

**Comment by RadDip** [comment] 2023-09-20 21:12
Beta version breaks the ability to turn off the fan in homekit

**Comment by zyonse** [comment] 2023-09-21 17:55
Does anything work on the beta version? Can you upload logs.

**Comment by RadDip** [comment] 2023-09-21 18:11
Everything works within the capabilities that I have for the plugin except power off.   I know that may not help much for as I mentioned in previous responses that I do not and have never had a separate Oscillation Button Slider from that of the Fan Power level.    As well as mentioned, I am using Hoobs and I am not able to create a log.  Hoobs is not letting me do it.

**Comment by ThatOneGuy808** [comment] 2023-09-24 08:15
I'm having the same problem with the oscillation button. It's not a big deal, but it is inconvenient. I'm not sure if it can be fixed or not. It might be a HomeKit thing. That would be dumb if the changed that to have oscillation in settings. I've attached your image from the GitHub page and a screenshot from my app

![image](https://github.com/zyonse/homebridge-dreo/assets/50556872/4a25753c-cb4f-4ac2-88af-dbe2273da53d)![image](https://github.com/zyonse/homebridge-dreo/assets/50556872/f1b91464-c6df-4871-a955-afe9ea8f1e60)![image](https://github.com/zyonse/homebridge-dreo/assets/50556872/235615de-8272-4db9-8c7e-1830f780505c)

**Comment by kapps7** [comment] 2023-10-14 04:15
It would be great to the oscillation function working. Happy to test!

**Comment by zyonse** [comment] 2023-10-31 18:26
This should be fixed in v3.1.0 thanks to @mganjoo. Let me know if it's working now.

**Comment by kapps7** [comment] 2023-11-03 10:39
Hey zyonse did you add the oscillation testing into the new version. Not seeing it. Otherwise the plugin works really well

**Comment by zyonse** [comment] 2023-11-06 15:19
@kapps It should be there, make sure you restart homebridge after updating.

**Comment by ThatOneGuy808** [comment] 2023-11-09 08:36
Hey I got the same issue. I'm not sure if I'm doing something wrong but I don't have oscillation buttons at all now. I reinstalled the plugin too

**Comment by zyonse** [comment] 2023-11-09 17:12
@ThatOneGuy808 In the screenshots you posted above, that's the intended behavior. The oscillation toggle got moved out of the main UI in iOS 17 and into the accessory settings. (not sure why)

However, it does look like the oscillation function was accidentally broken in one of the recent releases so I'll try to track down what's causing that.

**Comment by ThatOneGuy808** [comment] 2023-11-09 17:13
I see...so it was a HomeKit thing that they changed. Alright well hopefully you can figure out how to fix that. Thanks for looking into this. I guess now I know

**Comment by zyonse** [comment] 2023-11-09 17:22
@ThatOneGuy808 Can you go to "Tower Fan > Settings > Accessories > Tower Fan > Settings" and let me know if you see the oscillate toggle there? Just realized since we added the temperature sensor it changed the UI behavior a bit.

**Comment by ThatOneGuy808** [comment] 2023-11-09 17:46
@zyonse Yeah it's there now. Weird

**Closed** 2023-11-09 18:06 UTC
Labels: bug

**Comment by kapps7** [comment] 2023-11-10 04:07
Why can't you separate the accessories so they are visible in the home view as most grouped accessories can. 3 levels down to access oscillation.

**Comment by zyonse** [comment] 2023-11-10 04:28
It’s an iOS issue. The HomePod temperature sensor is grouped together the same way.

**Comment by ThatOneGuy808** [comment] 2023-11-10 04:35
HomeKit is great but man is it a pain in the butt. Ah well, you've done your best and I commend that. Thank you for what you are doing. Do you think it's possible to separate the sensor and fan so they appear as different devices? If not then it's not a big deal. I can always do it by other means

**Comment by kapps7** [comment] 2023-11-10 05:11
Anyway I am grateful for the plugin. Homekit is what it is and it's great most of the time. My second fan DR-HAF004S is not showing the oscillate function. It shows the linear fan speed only within the grouped fan accessory setting.

The first one  DR-HAF001S is showing it.

**Comment by kapps7** [comment] 2023-11-10 05:19
On the oscillation matter, You can create a scene (or automation) and the oscillation function is available in the accessory as. toggle  so you could easily call the scene to turn on/off oscillate. Problem addressed.

**Comment by johan456789** [comment] 2024-09-29 13:44
@zyonse Is DR-HAF001S officially supported? If so, it should be added to readme's list of compatible models.

**Comment by zyonse** [comment] 2024-09-29 16:13
@johan456789 Thanks for catching that, forgot to add it.
