### ISSUE TITLE
Support for MultiComfort Series 2-in-1 (Fan/Purifier) - DR-HTF010S

### ISSUE THREAD

**Issue by amulla928** [zyonse/homebridge-dreo#37] opened 2024-04-30 23:47 UTC
Wondering if support can be added for the Dreo Multicomfort Fan/Purifier

I am currently using Hoobs on Raspberry Pi 4, I can reimage it to run Homebridge instead if that's easier to work with.

Model Number: DR-HTF010S
Number of speeds the fan supports: 12
Does the fan support oscillating?: Yes
What preset modes are supported?
- The fan portion: Normal, Sleep, Auto, Breeze
- The purifier portion: Auto, 1, 2, 3
Is temperature supported?: Yes

Right now in the Home app, the fan speeds are not showing up.  The only thing I can tell is if the fan is on or off, it shows the fan speed as 0 if it's on. The temperature sensor does work.

If there's any additional information I can provide please let me know.  I'll need some guidance to get the logs, looks like debug mode in Hoobs is not working or something.  Might try switching to Homebridge.

**Comment by amulla928** [comment] 2024-05-01 00:32
Just switched to Homebridge.
I should note, that there was an error message in the logs.
This plugin generated a warning from the characteristic 'Rotation Speed': characteristic value expected valid finite number and received "NaN" (number).

**Comment by amulla928** [comment] 2024-05-01 00:48
Show your Homebridge config.json here, remove any sensitive information.
"platform": "DreoPlatform",
    "name": "Dreo Platform",
    "options": {
        "email": "",
        "password": ""

**Screenshots:**


**Environment:**
Homekit iOS 17.4.1

* **Plugin Version**: 3.2.5
* **Homebridge Version**:   1.8.1
* **Node.js Version**:  20.12.2
* **NPM Version**: 10.5.0
* **Operating System**:  Debian running on Raspberry Pi Model 4B with 4GB RAM

**Comment by zyonse** [comment] 2024-05-01 01:05
Were you able to get debug mode working? If you can send me some logs that show the device properties I might be able to add support.

**Comment by amulla928** [comment] 2024-05-01 01:08
> Were you able to get debug mode working? If you can send me some logs that show the device properties I might be able to add support.

[homebridge-dreo.log.txt](https://github.com/zyonse/homebridge-dreo/files/15172565/homebridge-dreo.log.txt)

hopefully this does not have any sensitive info

**Comment by amulla928** [comment] 2024-05-03 19:15
@zyonse just checking to see if you need any additional information or if that's all you need for now.

**Comment by zyonse** [comment] 2024-05-24 07:38
That's all I need for now, thanks.

**Comment by zyonse** [comment] 2024-07-16 21:24
Closing this as it's a duplicate of #8. I'd still like to add this functionality at some point but it's difficult without access to the device.

**Closed by zyonse** 2024-07-16 21:24 UTC
Labels: enhancement
