### ISSUE TITLE
Air Purifier (Macro Pro S)

### ISSUE THREAD

**Issue by cameronbowe** [zyonse/homebridge-dreo#22] opened 2023-11-03 00:01 UTC
Support for the Macro Pro S (DR-HAP002S) would be amazing!

**Comment by mark3apps** [comment] 2023-11-03 05:49
I can second this, supporting this would be amazingly helpful for my use.

**Comment by cameronbowe** [comment] 2023-11-03 08:38
It uses the following keys and values:

"aq" key with values 1-3 (1 Poor, 2 Moderate, 3 Excellent) - This is for air quality.
"windlevel" key with values 1-19 - This is for speed.
"mode" key with values "manual", "sleep", "turbo", "auto-regular" and "auto-silent" - Mode manual only happens when speed is selected, the auto modes are changed when you select "Standard" or "Soft" quiet mode, the auto mode automatically adjusts the fan speed based off the air quality.
"childlock" key with values True or False - This disables/enables the ability to press buttons on the device.
"ledalwayson" key with values True or False - This enables/disables the light on the device which displays the air quality.
"muteon" key with values True or False - This enables/disables the sounds the device makes.

I hope this helps :)

**Comment by zyonse** [comment] 2023-11-09 18:07
Duplicate of #8

**Closed by zyonse** 2023-11-09 18:07 UTC
Labels: enhancement
