### ISSUE TITLE
Please add support for Dreo Humidifier, Model: DR-HHM002S Blue

### ISSUE THREAD

**Issue by michael-mcnulty117** [zyonse/homebridge-dreo#43] opened 2024-06-25 15:54 UTC
**Is your feature request related to a problem? Please describe:**
No it's not related to a problem technically, it's just related to adding support for a device that is currently not supported by this plugin.

**Describe the solution you'd like:**
Add plugin support for the new Dreo Humidifier, Model: DR-HHM002S Blue

**Describe alternatives you've considered:**
n/a

**Additional context:**
I installed this plugin and configured it correctly, but in the Homebridge logs I get the message "[Dreo Platform] error: Unsupported device type  Humidifier" when it tries to connect. 

This humidifier may be relatively new, here's a link to the Amazon page for the model I received. 
https://www.amazon.com/dp/B0D2DLWKYW?psc=1&ref=ppx_yo2ov_dt_b_product_details

If it helps, I'm using this Humidifier with firmware version V3.2.4_0.3.9 and when I pull it up in the Apple Home app it shows up but can't do anything because it's not currently supported.

**Comment by zyonse** [comment] 2024-07-16 21:34
Duplicate of #28

**Closed by zyonse** 2024-07-16 21:34 UTC
Labels: enhancement
